services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Mappe le port 8501 du conteneur au port 8501 de l'hôte
    volumes:
      - .:/app # Monte le répertoire local dans le conteneur pour un développement en direct
      - /home/tramonihadrien/Dev/quant-dev/Cloud/quant-dev-442615-e7f3b4ab5908.json:/app/service-account-key.json
    environment:
      - FRED_API_KEY = ${FRED_API_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json
    # command:
    #   [
    #     "streamlit",
    #     "run",
    #     "app.py",
    #     "--server.port=8501",
    #     "--server.address=0.0.0.0",
    #   ]
    command: ["python3", "server.py"]
