services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"  # Mappe le port 8501 du conteneur au port 8501 de l'hôte
    volumes:
      - .:/app  # Monte le répertoire local dans le conteneur pour un développement en direct
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - FRED_API_KEY = ${FRED_API_KEY}
    command: ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]
